---
- hosts: all
  vars_files:
    - config.yml
  roles:
    - filebeat
    -
      role: deploybeta
      tags: [deploybeta]

- hosts: deploy1
  vars:
    registry:
      name: registry
      domain: registry.deploybeta.io
  roles:
    - registry

- hosts: deploy2
  vars:
    elasticsearch:
      name: es
      url: 'http://es.deploybeta.io:9200'
    kibana:
      name: kibana
      domain: kibana.deploybeta.io
  roles:
    - elasticsearch
    - kibana
