---
- hosts: all
  vars_files:
    - config.yml
  roles:
    -
      role: common
      tags: [common]
    -
      role: docker
      tags: [docker]
    -
      role: etcd
      tags: [etcd]
    -
      role: openresty
      tags: [openresty]
    -
      role: supervisor
      tags: [supervisor]
