---
- name: setup hostname
  hostname:
    name: '{{ inventory_hostname }}'

- name: setup iptables allow established
  iptables:
    table: filter
    chain: INPUT
    protocol: all
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT

- name: setup iptables allow ports
  iptables:
    table: filter
    chain: INPUT
    protocol: tcp
    destination_port: '{{ item }}'
    jump: ACCEPT
  with_items:
    - 22
    - 80
    - 443
    - 7000

- name: setup iptables allow icmp
  iptables:
    table: filter
    chain: INPUT
    protocol: icmp
    jump: ACCEPT

- name: setup iptables allow internal hosts
  iptables:
    table: filter
    chain: INPUT
    protocol: all
    source: '{{ internal_mask }}'
    jump: ACCEPT

- name: setup iptables allow loopback
  iptables:
    table: filter
    chain: INPUT
    protocol: all
    in_interface: lo
    jump: ACCEPT

- name: setup iptables policy
  iptables:
    table: filter
    chain: INPUT
    policy: DROP

- name: install apt packages
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'htop', 'software-properties-common', 'vim']

- name: ensures directory exists
  file:
    path: '/root/downloads'
    state: 'directory'
