---
- name: restart openresty
  service:
    name: 'openresty'
    state: restarted

- name: restart supervisor
  service:
    name: 'supervisor'
    state: restarted

- name: restart deploybeta
  supervisorctl:
    name: 'deploybeta'
    state: restarted

- name: build images
  shell: |
    docker build --tag registry.deploybeta.io/deploybeta-datasource-{{item}}:latest /home/deploybeta/assets/datasource-{{item}}
    docker push registry.deploybeta.io/deploybeta-datasource-{{item}}:latest
  with_items:
    - mongodb
    - redis
