#%RAML 1.0
title: Deploying API
version: v1
baseUri: https://deploying.cloud
mediaType: application/json

securitySchemes:
  sessionToken:
    type: Basic Authentication
    describedBy:
      headers:
        Authorization: string
      responses:
        401:

types:
  username:
    type: string
    pattern: ^[A-Za-z0-9_-]+$

  email: string

  account:
    properties:
      username: username
      email: email

  session:
    properties:
      username: username
      token: string

  application:
    properties:
      name: string
      owner: username
      gitRepository?: string
      instances: number
      version?: string
    
  image:
    properties: 
      shasum: string
      version: string


resourceTypes:
  Account:
    get:
      responses:
        200:
          body:
            type: account

  Accounts:
    post:
      body:
        properties:
          username: username
          password: string
          email: email
      responses:
        201:
          body:
            type: account
        400:
        409:

  Sessions:
    post:
      body:
        properties:
          username: username
          password: string
      responses:
        201:
          body:
            type: session
        401:

  Application:
    patch:
      body:
        properties:
          gitRepository?: string
          instances?: number
          version?: string
      responses:
        201:
          body:
            type: application
        409:

    delete:
      responses:
        200:

  Applications:
    get:
      responses:
        200:
          body:
            type: application[]

    post:
      body:
        properties:
          name: string
          gitRepository?: string
          instances: number
          version?: string
      responses:
        201:
          body:
            type: application
        409:

    Images:
      post:
        responses:
          201:
            body:
              type: image

/accounts:
  type: Accounts

/sessions:
  type: Sessions

/session/account:
  securedBy: [ sessionToken ]
  type: Account

/apps:
  securedBy: [ sessionToken ]
  type: Applications

  /{name}:
    type: Application
    
    /images:
      type: Images
